import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def code(source): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":source}
def md(source):   return {"cell_type":"markdown","metadata":{},"source":source}

cells = []

# ---------- HEADER ----------------------------------------------------------
cells.append(md([
    "# 07 ADR係数モデル — OLSによる最適ウェイト推定\n",
    "# ADR Coefficient Model — OLS-based Optimal Weight Estimation\n",
    "\n",
    "## 概要 / Overview\n",
    "\n",
    "ノートブック06では「Idea 1: 価格ウェイト」と「Idea 2: XGBoost」で日経平均を予測しました。  \n",
    "In notebook 06, we predicted Nikkei using price-based weights (Idea 1) and XGBoost (Idea 2).\n",
    "\n",
    "本ノートブックでは、**最小二乗法（OLS）でADR騰落率に乗じる係数を実績データから学習**します。  \n",
    "Here we learn coefficients for ADR returns via **OLS regression from historical data**.\n",
    "\n",
    "### なぜ係数モデルか / Why a coefficient model?\n",
    "\n",
    "| 手法 | ウェイトの決め方 | 解釈性 | データ適合性 |\n",
    "|------|-----------------|--------|--------------|\n",
    "| Idea 1（価格ウェイト） | 理論（プライスウェイト方式） | ◎ | △（固定） |\n",
    "| OLS係数モデル（本章） | 実績データから最小化 | ○ | ○（学習） |\n",
    "| XGBoost | 実績データ（非線形） | △ | ◎ |\n",
    "\n",
    "OLSは **「実際のデータでどのADRが日経と連動したか」** を定量化し、価格ウェイトとの差を分析できます。\n",
    "\n",
    "## モデル定義 / Model Definition\n",
    "\n",
    "$$\\hat{r}_{\\text{Nikkei, open}} = \\beta_0 + \\sum_{i=1}^{N} \\beta_i \\cdot r_i^{\\text{ADR(JPY)}} + \\varepsilon$$\n",
    "\n",
    "- $r_i^{\\text{ADR(JPY)}}$: ADR騰落率（USD建て）+ USDJPY騰落率 で JPY換算\n",
    "- $\\beta_i$: OLSで推定する係数（価格ウェイトとの比較対象）\n",
    "- ターゲット: `open_ret`（始値リターン）→ ノートブック06で最も予測精度が高かった\n",
    "\n",
    "## セクション構成\n",
    "\n",
    "| # | 内容 |\n",
    "|---|------|\n",
    "| 0 | 環境セットアップ |\n",
    "| 1 | データ取得 |\n",
    "| 2 | 特徴量エンジニアリング（06と同一）|\n",
    "| 3 | OLS係数の推定と統計的解釈 |\n",
    "| 4 | OLS係数 vs 価格ウェイトの比較 |\n",
    "| 5 | アウトオブサンプル評価 |\n",
    "| 6 | 考察 |\n",
]))

# ---------- STEP 0: packages ------------------------------------------------
cells.append(code([
    "# -- Step 0: Install packages -------------------------------------------\n",
    "import subprocess, sys\n",
    "\n",
    "pkgs = ['yfinance', 'scikit-learn>=1.5.0', 'statsmodels>=0.14.0']\n",
    "result = subprocess.run(\n",
    "    [sys.executable, '-m', 'pip', 'install', '-q'] + pkgs,\n",
    "    capture_output=True, text=True\n",
    ")\n",
    "out = result.stdout + result.stderr\n",
    "print(out.strip() if out.strip() else 'All packages already up to date.')\n",
]))

# ---------- STEP 0b: Colab --------------------------------------------------
cells.append(code([
    "# -- Step 0b: Repository & path setup ------------------------------------\n",
    "import os, sys\n",
    "\n",
    "REPO = '/content/Nikkei_Analysis'\n",
    "\n",
    "try:\n",
    "    import google.colab\n",
    "    IN_COLAB = True\n",
    "except ImportError:\n",
    "    IN_COLAB = False\n",
    "\n",
    "if IN_COLAB:\n",
    "    if not os.path.exists(REPO):\n",
    "        !git clone https://github.com/Takumi-Itokawa-Finance/Nikkei_Analysis.git {REPO}\n",
    "    else:\n",
    "        !git -C {REPO} pull\n",
    "    os.chdir(REPO)\n",
    "\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    DRIVE_DATA = '/content/drive/MyDrive/Nikkei_Analysis/data'\n",
    "    os.makedirs(DRIVE_DATA, exist_ok=True)\n",
    "    if not os.path.exists(f'{REPO}/data'):\n",
    "        os.symlink(DRIVE_DATA, f'{REPO}/data')\n",
    "\n",
    "    if REPO not in sys.path:\n",
    "        sys.path.insert(0, REPO)\n",
    "    print(f'Setup complete.  CWD={os.getcwd()}')\n",
    "else:\n",
    "    print('Running in local environment.')\n",
]))

# ---------- SECTION 1 -------------------------------------------------------
cells.append(md([
    "## 1. データ取得 / Data Collection\n",
    "\n",
    "ノートブック06と同一の銘柄・期間を使用します（データ準備コードは省略せず掲載）。\n",
]))

cells.append(code([
    "import warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.dates as mdates\n",
    "import yfinance as yf\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "pd.set_option('display.float_format', '{:.4f}'.format)\n",
    "plt.rcParams.update({'figure.dpi': 100, 'axes.grid': True, 'grid.alpha': 0.3})\n",
    "\n",
    "OUTPUT_FIGS = 'output/figures'\n",
    "os.makedirs(OUTPUT_FIGS, exist_ok=True)\n",
    "\n",
    "PERIOD = '3y'\n",
    "\n",
    "JP_ADR_MAP = {\n",
    "    '9983.T': 'FRCOY',\n",
    "    '8035.T': 'TOELY',\n",
    "    '9984.T': 'SFTBY',\n",
    "    '6954.T': 'FANUY',\n",
    "    '9433.T': 'KDDIY',\n",
    "    '4063.T': 'SHECY',\n",
    "    '6861.T': 'KYCCF',\n",
    "    '6367.T': 'DKILY',\n",
    "    '6857.T': 'ATEYY',\n",
    "    '6758.T': 'SONY',\n",
    "}\n",
    "\n",
    "JP_NAMES = {\n",
    "    '9983.T': 'FastRetailing',\n",
    "    '8035.T': 'TokyoElectron',\n",
    "    '9984.T': 'SoftBank',\n",
    "    '6954.T': 'Fanuc',\n",
    "    '9433.T': 'KDDIY',\n",
    "    '4063.T': 'ShinEtsu',\n",
    "    '6861.T': 'Keyence',\n",
    "    '6367.T': 'Daikin',\n",
    "    '6857.T': 'Advantest',\n",
    "    '6758.T': 'Sony',\n",
    "}\n",
    "\n",
    "US_MACRO = {'SP500': '^GSPC', 'NASDAQ': '^IXIC', 'VIX': '^VIX', 'USDJPY': 'JPY=X'}\n",
]))

cells.append(code([
    "def _clean(df):\n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.get_level_values(0)\n",
    "    idx = pd.to_datetime(df.index)\n",
    "    df.index = idx.tz_localize(None) if idx.tz is not None else idx\n",
    "    return df\n",
    "\n",
    "def fetch_ohlc(tickers, period, label):\n",
    "    frames = {}\n",
    "    failed = []\n",
    "    for t in tickers:\n",
    "        df = yf.download(t, period=period, interval='1d', progress=False, auto_adjust=True)\n",
    "        if len(df) > 10:\n",
    "            frames[t] = _clean(df)[['Open', 'Close']].copy()\n",
    "        else:\n",
    "            failed.append(t)\n",
    "    if failed:\n",
    "        print(f'[WARN] {label}: no data for {failed}')\n",
    "    return frames\n",
    "\n",
    "def fetch_close(tickers_dict, period):\n",
    "    frames = {}\n",
    "    for name, ticker in tickers_dict.items():\n",
    "        df = yf.download(ticker, period=period, interval='1d', progress=False, auto_adjust=True)\n",
    "        if len(df) > 10:\n",
    "            frames[name] = _clean(df)['Close'].squeeze()\n",
    "        else:\n",
    "            print(f'[WARN] No data for {name} ({ticker})')\n",
    "    return pd.DataFrame(frames)\n",
    "\n",
    "JP_TICKERS  = list(JP_ADR_MAP.keys())\n",
    "ADR_TICKERS = list(JP_ADR_MAP.values())\n",
    "\n",
    "print('Fetching Nikkei 225 OHLC ...')\n",
    "nikkei_raw = _clean(yf.download('^N225', period=PERIOD, interval='1d', progress=False, auto_adjust=True))\n",
    "\n",
    "print('Fetching Japanese stocks ...')\n",
    "jp_ohlc = fetch_ohlc(JP_TICKERS, PERIOD, 'JP stocks')\n",
    "\n",
    "print('Fetching ADRs ...')\n",
    "adr_ohlc = fetch_ohlc(ADR_TICKERS, PERIOD, 'ADRs')\n",
    "\n",
    "print('Fetching US macro ...')\n",
    "us_df = fetch_close(US_MACRO, PERIOD)\n",
    "\n",
    "valid_pairs = [\n",
    "    (jp_t, adr_t, JP_NAMES[jp_t])\n",
    "    for jp_t, adr_t in JP_ADR_MAP.items()\n",
    "    if jp_t in jp_ohlc and adr_t in adr_ohlc\n",
    "]\n",
    "print(f'Done. Valid pairs: {len(valid_pairs)} / {len(JP_ADR_MAP)}')\n",
]))

# ---------- SECTION 2 -------------------------------------------------------
cells.append(md([
    "## 2. 特徴量エンジニアリング / Feature Engineering\n",
    "\n",
    "ノートブック06と同一の処理：  \n",
    "- 日経ターゲット（始値・終値・場中リターン）  \n",
    "- ADR騰落率のFX調整（USD→JPY）  \n",
    "- 米国日付を+1営業日シフトして日本日付に対応  \n",
]))

cells.append(code([
    "# Nikkei targets\n",
    "nk = nikkei_raw[['Open', 'Close']].copy().dropna()\n",
    "nk.index = pd.to_datetime(nk.index)\n",
    "nk['open_ret']     = nk['Open']  / nk['Close'].shift(1) - 1\n",
    "nk['close_ret']    = nk['Close'] / nk['Close'].shift(1) - 1\n",
    "nk['intraday_ret'] = nk['Close'] / nk['Open']  - 1\n",
    "nk = nk.dropna()\n",
    "\n",
    "# ADR returns (USD) + USDJPY → JPY-adjusted ADR returns\n",
    "usdjpy_close = us_df['USDJPY'].dropna()\n",
    "usdjpy_ret   = usdjpy_close.pct_change()\n",
    "\n",
    "adr_ret_usd = {}\n",
    "for jp_t, adr_t, name in valid_pairs:\n",
    "    close_s = adr_ohlc[adr_t]['Close'].squeeze().dropna()\n",
    "    adr_ret_usd[name] = close_s.pct_change()\n",
    "\n",
    "adr_ret_df  = pd.DataFrame(adr_ret_usd)\n",
    "adr_ret_jpy = adr_ret_df.add(usdjpy_ret, axis=0)  # JPY = USD + USDJPY\n",
    "\n",
    "# US macro returns\n",
    "us_macro_ret = us_df[['SP500', 'NASDAQ', 'VIX']].pct_change()\n",
    "us_macro_ret['USDJPY'] = usdjpy_ret\n",
    "\n",
    "# Shift US dates +1 business day to align with Japan dates\n",
    "def shift_us_to_jp(df):\n",
    "    shifted = df.copy()\n",
    "    shifted.index = df.index + pd.tseries.offsets.BDay(1)\n",
    "    return shifted\n",
    "\n",
    "adr_jpy_shifted  = shift_us_to_jp(adr_ret_jpy)\n",
    "us_macro_shifted = shift_us_to_jp(us_macro_ret)\n",
    "\n",
    "# Merge on Japan dates\n",
    "targets = nk[['open_ret', 'close_ret', 'intraday_ret']]\n",
    "feat = targets.join(adr_jpy_shifted, how='inner').join(us_macro_shifted, how='inner').dropna()\n",
    "\n",
    "ADR_NAMES    = [name for _, _, name in valid_pairs]\n",
    "MACRO_COLS   = ['SP500', 'NASDAQ', 'VIX', 'USDJPY']\n",
    "FEATURE_COLS = ADR_NAMES + MACRO_COLS\n",
    "\n",
    "print(f'Dataset: {feat.shape}')\n",
    "print(f'Period : {feat.index[0].date()} to {feat.index[-1].date()}')\n",
    "print(f'ADRs   : {ADR_NAMES}')\n",
]))

# ---------- SECTION 3 -------------------------------------------------------
cells.append(md([
    "## 3. OLS係数の推定と統計的解釈\n",
    "\n",
    "### ターゲット: 始値リターン (`open_ret`)\n",
    "\n",
    "ノートブック06の結果から、**始値リターンが最も予測精度が高い**ことが確認されています。  \n",
    "ADRは日本時間8時（米国クローズ後）に入手可能で、始値（9時）までの3時間で情報は十分に織り込まれます。\n",
    "\n",
    "### statsmodelsによるOLS\n",
    "\n",
    "- 係数の標準誤差・t統計量・p値を確認\n",
    "- **R²**: ADRのみでどれだけ始値リターンを説明できるか\n",
    "- **有意な係数** (p < 0.05) のADRが「統計的に意味のある予測因子」\n",
    "\n",
    "> ⚠️ これはフルサンプルのin-sample分析です。アウトオブサンプル評価はセクション5で行います。\n",
]))

cells.append(code([
    "import statsmodels.api as sm\n",
    "\n",
    "y = feat['open_ret']\n",
    "\n",
    "# Model A: ADR returns only\n",
    "X_adr = sm.add_constant(feat[ADR_NAMES])\n",
    "ols_adr = sm.OLS(y, X_adr).fit()\n",
    "\n",
    "# Model B: ADR + macro\n",
    "X_full = sm.add_constant(feat[FEATURE_COLS])\n",
    "ols_full = sm.OLS(y, X_full).fit()\n",
    "\n",
    "print('=== Model A: ADR returns only ===')\n",
    "print(f'R²          : {ols_adr.rsquared:.4f}')\n",
    "print(f'Adj. R²     : {ols_adr.rsquared_adj:.4f}')\n",
    "print(f'Observations: {int(ols_adr.nobs)}')\n",
    "print()\n",
    "print('=== Model B: ADR + Macro ===')\n",
    "print(f'R²          : {ols_full.rsquared:.4f}')\n",
    "print(f'Adj. R²     : {ols_full.rsquared_adj:.4f}')\n",
    "print(f'Observations: {int(ols_full.nobs)}')\n",
]))

cells.append(code([
    "# OLS coefficient table for Model A (ADR only) with significance stars\n",
    "coef_table = pd.DataFrame({\n",
    "    'Coef':   ols_adr.params[ADR_NAMES],\n",
    "    'Std Err':ols_adr.bse[ADR_NAMES],\n",
    "    't-stat': ols_adr.tvalues[ADR_NAMES],\n",
    "    'p-value':ols_adr.pvalues[ADR_NAMES],\n",
    "})\n",
    "\n",
    "def sig_stars(p):\n",
    "    if p < 0.001: return '***'\n",
    "    if p < 0.01:  return '**'\n",
    "    if p < 0.05:  return '*'\n",
    "    if p < 0.10:  return '.'\n",
    "    return ''\n",
    "\n",
    "coef_table['Sig'] = coef_table['p-value'].apply(sig_stars)\n",
    "coef_table = coef_table.sort_values('Coef', ascending=False)\n",
    "\n",
    "print('OLS Coefficients — Model A (ADR only, target: open_ret)')\n",
    "print('Signif. codes: *** p<0.001  ** p<0.01  * p<0.05  . p<0.10')\n",
    "print()\n",
    "display(\n",
    "    coef_table.style\n",
    "    .format({'Coef': '{:+.4f}', 'Std Err': '{:.4f}',\n",
    "             't-stat': '{:+.2f}', 'p-value': '{:.4f}'})\n",
    "    .background_gradient(subset=['Coef'], cmap='RdBu')\n",
    ")\n",
]))

# ---------- SECTION 4 -------------------------------------------------------
cells.append(md([
    "## 4. OLS係数 vs 価格ウェイトの比較\n",
    "\n",
    "日経225はプライスウェイト方式のため、理論的には：\n",
    "\n",
    "$$w_i^{\\text{price}} = \\frac{P_i}{\\sum_j P_j}$$\n",
    "\n",
    "が各銘柄の「寄与係数」です。  \n",
    "OLS係数 $\\hat{\\beta}_i$ との差を見ることで、**どの銘柄が理論より強く/弱く日経に影響しているか**を把握できます。\n",
    "\n",
    "### 注意点\n",
    "- 価格ウェイト $w_i$ の単位は「全体に対するシェア」（合計=1）\n",
    "- OLS係数 $\\hat{\\beta}_i$ の単位は「ADR1%変化 → 日経X%変化」  \n",
    "  → 直接比較のため、OLS係数を合計が1になるよう正規化して比較します\n",
]))

cells.append(code([
    "# Compute average price weights from JP stock data\n",
    "jp_close_dict = {}\n",
    "for jp_t, adr_t, name in valid_pairs:\n",
    "    s = jp_ohlc[jp_t]['Close'].squeeze().dropna()\n",
    "    s.index = pd.to_datetime(s.index)\n",
    "    jp_close_dict[name] = s\n",
    "\n",
    "jp_close = pd.DataFrame(jp_close_dict)\n",
    "# Mean price weight over the full period (for reference)\n",
    "avg_prices  = jp_close.reindex(feat.index).mean()\n",
    "price_weights = avg_prices / avg_prices.sum()\n",
    "\n",
    "# OLS coefficients (positive values only; clip negative to 0 for comparison)\n",
    "ols_coefs = ols_adr.params[ADR_NAMES]\n",
    "\n",
    "# Normalize OLS coefficients so they sum to 1 (for visual comparison with price weights)\n",
    "ols_pos = ols_coefs.clip(lower=0)\n",
    "ols_normalized = ols_pos / ols_pos.sum() if ols_pos.sum() > 0 else ols_pos\n",
    "\n",
    "cmp_df = pd.DataFrame({\n",
    "    'OLS_coef':        ols_coefs,\n",
    "    'OLS_normalized':  ols_normalized,\n",
    "    'PriceWeight':     price_weights,\n",
    "}).sort_values('PriceWeight', ascending=False)\n",
    "\n",
    "print('Coefficient Comparison Table')\n",
    "print('(OLS_normalized: OLS coefficients normalised to sum to 1 for comparison with PriceWeight)')\n",
    "print()\n",
    "display(\n",
    "    cmp_df.style\n",
    "    .format({'OLS_coef': '{:+.4f}', 'OLS_normalized': '{:.4f}', 'PriceWeight': '{:.4f}'})\n",
    "    .background_gradient(subset=['OLS_normalized', 'PriceWeight'], cmap='Blues')\n",
    ")\n",
]))

cells.append(code([
    "# Bar chart: OLS_normalized vs PriceWeight\n",
    "names = cmp_df.index.tolist()\n",
    "x = np.arange(len(names))\n",
    "w = 0.35\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(12, 5))\n",
    "bars1 = ax.bar(x - w/2, cmp_df['PriceWeight'],     width=w, label='Price Weight (Idea 1)',    color='steelblue',   alpha=0.85)\n",
    "bars2 = ax.bar(x + w/2, cmp_df['OLS_normalized'],  width=w, label='OLS Coef (Normalised)',    color='darkorange',  alpha=0.85)\n",
    "\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(names, rotation=30, ha='right', fontsize=9)\n",
    "ax.set_ylabel('Weight')\n",
    "ax.set_title('Price Weight vs Normalised OLS Coefficient')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/07_01_weight_comparison.png', dpi=150)\n",
    "plt.show()\n",
    "\n",
    "# Interpretation\n",
    "print('\\nInterpretation:')\n",
    "print('- PriceWeight > OLS_normalized: large by price but relatively weak predictor')\n",
    "print('- OLS_normalized > PriceWeight: correlates with Nikkei open more than its price share suggests')\n",
]))

# ---------- SECTION 5 -------------------------------------------------------
cells.append(md([
    "## 5. アウトオブサンプル評価 / Out-of-Sample Evaluation\n",
    "\n",
    "フルサンプルでOLSを当てはめても、過去に合わせすぎた「過学習」のリスクがあります。  \n",
    "ここでは：\n",
    "\n",
    "1. **単純分割**: 直近252日をテストセット、それ以前をトレーニングセットとして評価\n",
    "2. 比較対象: Idea 1（価格ウェイト）・OLS-ADRのみ・OLS-ADR+マクロ\n",
    "\n",
    "### 評価指標\n",
    "| 指標 | 定義 |\n",
    "|------|------|\n",
    "| RMSE | 予測誤差の二乗平均平方根（小さいほど良い）|\n",
    "| 相関係数 | 予測値と実績値の線形相関（高いほど良い）|\n",
    "| 方向一致率 | 上昇/下落の方向が一致した割合（50%が無作為）|\n",
]))

cells.append(code([
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "TEST_SIZE = 252\n",
    "feat_train = feat.iloc[:-TEST_SIZE]\n",
    "feat_test  = feat.iloc[-TEST_SIZE:]\n",
    "\n",
    "y_train = feat_train['open_ret']\n",
    "y_test  = feat_test['open_ret']\n",
    "\n",
    "print(f'Train: {feat_train.index[0].date()} to {feat_train.index[-1].date()}  ({len(feat_train)} days)')\n",
    "print(f'Test : {feat_test.index[0].date()}  to {feat_test.index[-1].date()}   ({len(feat_test)} days)')\n",
]))

cells.append(code([
    "# --- Idea 1: Price-weight (same as notebook 06) ---------------------------\n",
    "jp_price_prev = jp_close.shift(1)\n",
    "total_prev    = jp_price_prev.sum(axis=1)\n",
    "jp_weights    = jp_price_prev.div(total_prev, axis=0)\n",
    "jp_wt_aligned = jp_weights.reindex(feat.index).ffill()\n",
    "\n",
    "common = [n for n in ADR_NAMES if n in jp_wt_aligned.columns]\n",
    "synthetic_ret = (jp_wt_aligned[common] * feat[common]).sum(axis=1)\n",
    "\n",
    "# --- OLS models: fit on train, predict on test ----------------------------\n",
    "lr_adr  = LinearRegression().fit(feat_train[ADR_NAMES],    y_train)\n",
    "lr_full = LinearRegression().fit(feat_train[FEATURE_COLS], y_train)\n",
    "\n",
    "pred_idea1   = synthetic_ret.loc[feat_test.index]\n",
    "pred_ols_adr = lr_adr.predict(feat_test[ADR_NAMES])\n",
    "pred_ols_full= lr_full.predict(feat_test[FEATURE_COLS])\n",
    "\n",
    "def eval_metrics(y_true, y_pred, label):\n",
    "    y_true = np.array(y_true)\n",
    "    y_pred = np.array(y_pred)\n",
    "    mask   = ~(np.isnan(y_true) | np.isnan(y_pred))\n",
    "    yt, yp = y_true[mask], y_pred[mask]\n",
    "    rmse    = np.sqrt(mean_squared_error(yt, yp))\n",
    "    corr    = np.corrcoef(yp, yt)[0, 1]\n",
    "    dir_acc = (np.sign(yp) == np.sign(yt)).mean()\n",
    "    sharpe  = (np.sign(yp) * yt).mean() / ((np.sign(yp) * yt).std() + 1e-10) * np.sqrt(252)\n",
    "    return {'Method': label, 'RMSE': rmse, 'Correlation': corr, 'Dir. Accuracy': dir_acc, 'Sharpe': sharpe}\n",
    "\n",
    "results = pd.DataFrame([\n",
    "    eval_metrics(y_test, pred_idea1,    'Idea 1: Price Weight'),\n",
    "    eval_metrics(y_test, pred_ols_adr,  'OLS-A:  ADR only'),\n",
    "    eval_metrics(y_test, pred_ols_full, 'OLS-B:  ADR + Macro'),\n",
    "]).set_index('Method')\n",
    "\n",
    "print('=== Out-of-Sample Evaluation (Test period: last 252 trading days) ===')\n",
    "display(\n",
    "    results.style\n",
    "    .format({'RMSE': '{:.4f}', 'Correlation': '{:.3f}', 'Dir. Accuracy': '{:.3f}', 'Sharpe': '{:.2f}'})\n",
    "    .background_gradient(subset=['Dir. Accuracy'], cmap='RdYlGn')\n",
    "    .background_gradient(subset=['Correlation'],   cmap='RdYlGn')\n",
    "    .background_gradient(subset=['Sharpe'],      cmap='RdYlGn')\n",
    ")\n",
]))

cells.append(code([
    "# Time series of predictions vs actual (test period)\n",
    "fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n",
    "\n",
    "pairs = [\n",
    "    (pred_idea1,    'Idea 1: Price Weight', 'steelblue'),\n",
    "    (pred_ols_adr,  'OLS-A: ADR only',      'darkorange'),\n",
    "    (pred_ols_full, 'OLS-B: ADR + Macro',   'green'),\n",
    "]\n",
    "\n",
    "for ax, (pred, label, color) in zip(axes, pairs):\n",
    "    ax.plot(feat_test.index, y_test.values,          color='black',  lw=1.0,  label='Actual', alpha=0.7)\n",
    "    ax.plot(feat_test.index, np.array(pred),         color=color,    lw=1.0,  label=label)\n",
    "    ax.axhline(0, color='grey', lw=0.5, ls='--')\n",
    "    ax.set_ylabel('Return')\n",
    "    ax.legend(loc='upper left', fontsize=8)\n",
    "    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))\n",
    "\n",
    "axes[0].set_title('Open Return: Prediction vs Actual (Test Period)')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/07_02_oos_timeseries.png', dpi=150)\n",
    "plt.show()\n",
]))

cells.append(code([
    "# Scatter plots: prediction vs actual for each model\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
    "\n",
    "for ax, (pred, label, color) in zip(axes, pairs):\n",
    "    yp = np.array(pred)\n",
    "    yt = y_test.values\n",
    "    mask = ~(np.isnan(yp) | np.isnan(yt))\n",
    "    yp, yt = yp[mask], yt[mask]\n",
    "\n",
    "    corr = np.corrcoef(yp, yt)[0, 1]\n",
    "    dir_acc = (np.sign(yp) == np.sign(yt)).mean()\n",
    "\n",
    "    ax.scatter(yp, yt, s=8, alpha=0.4, color=color)\n",
    "    # Regression line\n",
    "    m, b = np.polyfit(yp, yt, 1)\n",
    "    xr = np.array([yp.min(), yp.max()])\n",
    "    ax.plot(xr, m * xr + b, color='black', lw=1.2)\n",
    "    ax.axhline(0, color='grey', lw=0.5); ax.axvline(0, color='grey', lw=0.5)\n",
    "    ax.set_xlabel('Predicted')\n",
    "    ax.set_ylabel('Actual')\n",
    "    ax.set_title(f'{label}\\nr={corr:.3f}  dir={dir_acc:.3f}')\n",
    "\n",
    "plt.suptitle('Scatter: Predicted vs Actual (Test Period)', y=1.02)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/07_03_scatter.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
]))

# ---------- SECTION 6 -------------------------------------------------------
cells.append(md([
    "## 6. 考察 / Discussion\n",
    "\n",
    "### まとめ\n",
    "\n",
    "| 観点 | 結果と解釈 |\n",
    "|------|----------|\n",
    "| **フルサンプルR²** | ADRのみで始値リターンの分散をある程度説明できる |\n",
    "| **OLS係数 vs 価格ウェイト** | 理論と実績の乖離が見える — 一部のADRは価格シェア以上に情報を持つ |\n",
    "| **OOSパフォーマンス** | Idea 1との比較でOLSの優位性（または限界）が確認できる |\n",
    "\n",
    "### OLSの限界\n",
    "\n",
    "1. **多重共線性**: ADR間の相関が高い（同一セクター）と係数が不安定になる\n",
    "   → 対策: ノートブック04/06のRidge回帰（L2正則化）\n",
    "\n",
    "2. **係数の時間変動**: 市場環境（リスクオン/オフ）によって $\\beta_i$ は変化する\n",
    "   → 対策: ローリングOLS（窓幅252日など）で時変係数を推定\n",
    "\n",
    "3. **非線形関係**: 急落時・急騰時の挙動が平常時と異なる\n",
    "   → 対策: XGBoost（ノートブック06 Idea 2）\n",
    "\n",
    "4. **カバレッジ問題**: 上位10銘柄のADRのみで日経全体の約60-70%をカバー\n",
    "   → 残りはSP500/NASDAQなどマクロ指標で補完（OLS-B モデル）\n",
    "\n",
    "### 実務的な使い方\n",
    "\n",
    "日本時間8時のADR終値を確認 → OLS係数モデルで始値リターンを推定 →  \n",
    "**方向一致率が50%を大幅に超えるなら** 「今日の寄り付きは強そう/弱そう」という判断材料になりえます。\n",
    "\n",
    "> **免責**: 本ノートブックは教育目的です。実際の投資判断には使用しないでください。\n",
]))

# ---------- NOTEBOOK JSON ---------------------------------------------------
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
    },
    "cells": cells,
}

out_path = r'C:\Users\admin\Nikkei_Analysis\notebooks\07_adr_coefficients.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print('07_adr_coefficients.ipynb created')
