import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def code(source): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":source}
def md(source):   return {"cell_type":"markdown","metadata":{},"source":source}

cells = []

# ---------- HEADER ----------------------------------------------------------
cells.append(md([
    "# 08 終値予測とレンジ推定 / Close Price Prediction with Prediction Interval\n",
    "\n",
    "## 概要 / Overview\n",
    "\n",
    "これまでの分析（ADR特徴量・テクニカル指標・マクロ指標）を統合し、  \n",
    "**当日の日経225終値と予測レンジ（90% 予測区間）** を出力します。\n",
    "\n",
    "## 予測ロジック / Prediction Logic\n",
    "\n",
    "| 情報源 | 特徴量 | 利用可能時刻 |\n",
    "|--------|--------|-------------|\n",
    "| ADR騰落率 | 10銘柄 × JPY換算リターン | 8:00 JST |\n",
    "| 米国マクロ | SP500 / NASDAQ / VIX / USDJPY | 8:00 JST |\n",
    "| テクニカル指標 | RSI / MACD / BB位置 / モメンタム | 前日確定 |\n",
    "\n",
    "すべて **寄り付き（9:00 JST）前** に入手可能な情報のみを使用します。\n",
    "\n",
    "## アウトプット / Output\n",
    "\n",
    "```\n",
    "=== 本日(YYYY-MM-DD)の日経225終値予測 ===\n",
    "前日終値:    XX,XXX 円\n",
    "予測終値:    XX,XXX 円  (+X.XX%)\n",
    "\n",
    "予測レンジ (90% 予測区間):\n",
    "  下限 ( 5%): XX,XXX 円  (-X.XX%)\n",
    "  中央 (50%): XX,XXX 円  (+X.XX%)\n",
    "  上限 (95%): XX,XXX 円  (+X.XX%)\n",
    "```\n",
    "\n",
    "## セクション構成\n",
    "\n",
    "| # | 内容 |\n",
    "|---|------|\n",
    "| 0 | 環境セットアップ |\n",
    "| 1 | データ取得 |\n",
    "| 2 | テクニカル指標の計算 |\n",
    "| 3 | 特徴量マトリクスの構築 |\n",
    "| 4 | OLSモデルの学習 |\n",
    "| 5 | 予測区間のバックテスト（カバレッジ確認）|\n",
    "| 6 | 本日の終値予測（メイン出力）|\n",
]))

# ---------- STEP 0 ----------------------------------------------------------
cells.append(code([
    "# -- Step 0: Install packages -------------------------------------------\n",
    "import subprocess, sys\n",
    "\n",
    "pkgs = ['yfinance', 'scikit-learn>=1.5.0', 'statsmodels>=0.14.0']\n",
    "result = subprocess.run(\n",
    "    [sys.executable, '-m', 'pip', 'install', '-q'] + pkgs,\n",
    "    capture_output=True, text=True\n",
    ")\n",
    "out = result.stdout + result.stderr\n",
    "print(out.strip() if out.strip() else 'All packages already up to date.')\n",
]))

cells.append(code([
    "# -- Step 0b: Repository & path setup ------------------------------------\n",
    "import os, sys\n",
    "\n",
    "REPO = '/content/Nikkei_Analysis'\n",
    "\n",
    "try:\n",
    "    import google.colab\n",
    "    IN_COLAB = True\n",
    "except ImportError:\n",
    "    IN_COLAB = False\n",
    "\n",
    "if IN_COLAB:\n",
    "    if not os.path.exists(REPO):\n",
    "        !git clone https://github.com/Takumi-Itokawa-Finance/Nikkei_Analysis.git {REPO}\n",
    "    else:\n",
    "        !git -C {REPO} pull\n",
    "    os.chdir(REPO)\n",
    "\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    DRIVE_DATA = '/content/drive/MyDrive/Nikkei_Analysis/data'\n",
    "    os.makedirs(DRIVE_DATA, exist_ok=True)\n",
    "    if not os.path.exists(f'{REPO}/data'):\n",
    "        os.symlink(DRIVE_DATA, f'{REPO}/data')\n",
    "\n",
    "    if REPO not in sys.path:\n",
    "        sys.path.insert(0, REPO)\n",
    "    print(f'Setup complete.  CWD={os.getcwd()}')\n",
    "else:\n",
    "    print('Running in local environment.')\n",
]))

# ---------- SECTION 1 -------------------------------------------------------
cells.append(md([
    "## 1. データ取得 / Data Collection\n",
]))

cells.append(code([
    "import warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.dates as mdates\n",
    "import statsmodels.api as sm\n",
    "import yfinance as yf\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "pd.set_option('display.float_format', '{:.4f}'.format)\n",
    "plt.rcParams.update({'figure.dpi': 100, 'axes.grid': True, 'grid.alpha': 0.3})\n",
    "\n",
    "OUTPUT_FIGS = 'output/figures'\n",
    "os.makedirs(OUTPUT_FIGS, exist_ok=True)\n",
    "\n",
    "PERIOD = '3y'\n",
    "\n",
    "JP_ADR_MAP = {\n",
    "    '9983.T': ('FRCOY', 'FastRetailing'),\n",
    "    '8035.T': ('TOELY', 'TokyoElectron'),\n",
    "    '9984.T': ('SFTBY', 'SoftBank'),\n",
    "    '6954.T': ('FANUY', 'Fanuc'),\n",
    "    '9433.T': ('KDDIY', 'KDDI'),\n",
    "    '4063.T': ('SHECY', 'ShinEtsu'),\n",
    "    '6861.T': ('KYCCF', 'Keyence'),\n",
    "    '6367.T': ('DKILY', 'Daikin'),\n",
    "    '6857.T': ('ATEYY', 'Advantest'),\n",
    "    '6758.T': ('SONY',  'Sony'),\n",
    "}\n",
    "\n",
    "US_MACRO = {'SP500': '^GSPC', 'NASDAQ': '^IXIC', 'VIX': '^VIX', 'USDJPY': 'JPY=X'}\n",
]))

cells.append(code([
    "def _clean(df):\n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.get_level_values(0)\n",
    "    idx = pd.to_datetime(df.index)\n",
    "    df.index = idx.tz_localize(None) if idx.tz is not None else idx\n",
    "    return df\n",
    "\n",
    "def yf_ohlcv(ticker, period):\n",
    "    df = yf.download(ticker, period=period, interval='1d', progress=False, auto_adjust=True)\n",
    "    return _clean(df) if len(df) > 10 else None\n",
    "\n",
    "def yf_close(tickers_dict, period):\n",
    "    frames = {}\n",
    "    for name, ticker in tickers_dict.items():\n",
    "        df = yf.download(ticker, period=period, interval='1d', progress=False, auto_adjust=True)\n",
    "        if len(df) > 10:\n",
    "            frames[name] = _clean(df)['Close'].squeeze()\n",
    "        else:\n",
    "            print(f'[WARN] No data: {name} ({ticker})')\n",
    "    return pd.DataFrame(frames)\n",
    "\n",
    "print('Fetching Nikkei 225 ...')\n",
    "nk_raw = yf_ohlcv('^N225', PERIOD)\n",
    "\n",
    "print('Fetching ADRs ...')\n",
    "adr_data = {}\n",
    "valid_pairs = []\n",
    "for jp_t, (adr_t, name) in JP_ADR_MAP.items():\n",
    "    df = yf_ohlcv(adr_t, PERIOD)\n",
    "    if df is not None:\n",
    "        adr_data[name] = df['Close'].squeeze()\n",
    "        valid_pairs.append(name)\n",
    "    else:\n",
    "        print(f'[WARN] No ADR data: {name} ({adr_t})')\n",
    "\n",
    "print('Fetching US macro ...')\n",
    "us_df = yf_close(US_MACRO, PERIOD)\n",
    "\n",
    "print(f'Done. Nikkei rows: {len(nk_raw)}, ADRs: {len(valid_pairs)}/10')\n",
]))

# ---------- SECTION 2 -------------------------------------------------------
cells.append(md([
    "## 2. テクニカル指標の計算 / Technical Indicators\n",
    "\n",
    "前日確定の指標を特徴量として使用します（当日データを使わない = ルックアヘッドなし）。\n",
    "\n",
    "| 指標 | パラメータ | 意味 |\n",
    "|------|------------|------|\n",
    "| RSI | 14日 | 過熱・売られすぎの度合い |\n",
    "| MACD histogram | EMA(12,26,9) | モメンタムの強弱 |\n",
    "| ボリンジャーバンド位置 | 20日 | バンド内の相対位置（-1〜+1） |\n",
    "| 価格モメンタム | 5日・20日 | 短期・中期の騰落率 |\n",
    "| 出来高比率 | 20日平均比 | 売買参加度 |\n",
]))

cells.append(code([
    "nk = nk_raw[['Open', 'High', 'Low', 'Close', 'Volume']].copy().dropna()\n",
    "nk.index = pd.to_datetime(nk.index)\n",
    "\n",
    "# --- RSI(14) ---\n",
    "delta = nk['Close'].diff()\n",
    "gain  = delta.clip(lower=0).rolling(14).mean()\n",
    "loss  = (-delta.clip(upper=0)).rolling(14).mean()\n",
    "nk['RSI'] = 100 - (100 / (1 + gain / loss.replace(0, np.nan)))\n",
    "\n",
    "# --- MACD histogram ---\n",
    "ema12 = nk['Close'].ewm(span=12, adjust=False).mean()\n",
    "ema26 = nk['Close'].ewm(span=26, adjust=False).mean()\n",
    "macd  = ema12 - ema26\n",
    "nk['MACD_hist'] = macd - macd.ewm(span=9, adjust=False).mean()\n",
    "\n",
    "# --- Bollinger Band position: 0=mid, ±1=bands ---\n",
    "ma20  = nk['Close'].rolling(20).mean()\n",
    "std20 = nk['Close'].rolling(20).std()\n",
    "nk['BB_pos'] = (nk['Close'] - ma20) / (2 * std20.replace(0, np.nan))\n",
    "\n",
    "# --- Momentum ---\n",
    "nk['Mom5']  = nk['Close'].pct_change(5)\n",
    "nk['Mom20'] = nk['Close'].pct_change(20)\n",
    "\n",
    "# --- Volume ratio ---\n",
    "vol_ma = nk['Volume'].rolling(20).mean()\n",
    "nk['Vol_ratio'] = nk['Volume'] / vol_ma.replace(0, np.nan)\n",
    "\n",
    "# --- Daily return targets ---\n",
    "nk['open_ret']  = nk['Open']  / nk['Close'].shift(1) - 1\n",
    "nk['close_ret'] = nk['Close'] / nk['Close'].shift(1) - 1\n",
    "\n",
    "TECH_COLS = ['RSI', 'MACD_hist', 'BB_pos', 'Mom5', 'Mom20', 'Vol_ratio']\n",
    "print('Technical indicators:')\n",
    "print(nk[TECH_COLS].describe().round(4))\n",
]))

# ---------- SECTION 3 -------------------------------------------------------
cells.append(md([
    "## 3. 特徴量マトリクスの構築 / Feature Matrix\n",
    "\n",
    "各行（日本日付 T）の特徴量：\n",
    "\n",
    "| カテゴリ | 特徴量 | タイムスタンプ |\n",
    "|----------|--------|---------------|\n",
    "| テクニカル | RSI, MACD_hist, BB_pos, Mom5, Mom20, Vol_ratio | T−1（前日確定値を shift(1)）|\n",
    "| ADR | 10銘柄の JPY 換算騰落率 | US日付 T−1 → +1営業日シフト |\n",
    "| マクロ | SP500, NASDAQ, VIX, USDJPY 騰落率 | US日付 T−1 → +1営業日シフト |\n",
    "| ターゲット | `close_ret` = 終値騰落率 | T（当日）|\n",
]))

cells.append(code([
    "# --- ADR returns (USD) → JPY-adjusted ---\n",
    "usdjpy_ret = us_df['USDJPY'].pct_change()\n",
    "\n",
    "adr_ret_jpy = pd.DataFrame({\n",
    "    name: pd.Series(adr_data[name]).pct_change().add(usdjpy_ret)\n",
    "    for name in valid_pairs\n",
    "})\n",
    "\n",
    "# --- US macro returns ---\n",
    "us_macro_ret = us_df[['SP500', 'NASDAQ', 'VIX']].pct_change()\n",
    "us_macro_ret['USDJPY'] = usdjpy_ret\n",
    "\n",
    "# --- Shift US data +1 business day ---\n",
    "def shift_us(df):\n",
    "    s = df.copy()\n",
    "    s.index = df.index + pd.tseries.offsets.BDay(1)\n",
    "    return s\n",
    "\n",
    "adr_shifted   = shift_us(adr_ret_jpy)\n",
    "macro_shifted = shift_us(us_macro_ret)\n",
    "\n",
    "# --- Tech features: lag-1 (shift by 1 row to avoid look-ahead) ---\n",
    "tech_lag = nk[TECH_COLS].shift(1)\n",
    "\n",
    "# --- Merge all on Japan dates ---\n",
    "targets = nk[['close_ret', 'open_ret']]\n",
    "feat = (\n",
    "    targets\n",
    "    .join(tech_lag,      how='inner')\n",
    "    .join(adr_shifted,   how='inner')\n",
    "    .join(macro_shifted, how='inner')\n",
    "    .dropna()\n",
    ")\n",
    "\n",
    "MACRO_COLS   = ['SP500', 'NASDAQ', 'VIX', 'USDJPY']\n",
    "FEATURE_COLS = TECH_COLS + valid_pairs + MACRO_COLS\n",
    "\n",
    "print(f'Feature matrix: {feat.shape}')\n",
    "print(f'Period        : {feat.index[0].date()} to {feat.index[-1].date()}')\n",
    "print(f'Features ({len(FEATURE_COLS)}): {FEATURE_COLS}')\n",
]))

cells.append(code([
    "# Correlation of each feature with close_ret\n",
    "corr = feat[FEATURE_COLS].corrwith(feat['close_ret'])\n",
    "corr_sorted = corr.abs().sort_values(ascending=False)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "colors = ['steelblue' if c >= 0 else 'tomato'\n",
    "          for c in corr.loc[corr_sorted.index]]\n",
    "ax.barh(corr_sorted.index, corr.loc[corr_sorted.index], color=colors)\n",
    "ax.axvline(0, color='black', lw=0.8)\n",
    "ax.set_xlabel('Pearson Correlation (with Close Return)')\n",
    "ax.set_title('Feature Correlation with Close Return (close_ret)')\n",
    "ax.invert_yaxis()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/08_01_feature_correlation.png', dpi=150)\n",
    "plt.show()\n",
]))

# ---------- SECTION 4 -------------------------------------------------------
cells.append(md([
    "## 4. OLSモデルの学習 / OLS Model Training\n",
    "\n",
    "statsmodels の OLS を使う理由：\n",
    "- **予測区間（prediction interval）** を標準的な統計手法で計算できる\n",
    "- `get_prediction()` が返す `obs_ci_lower / obs_ci_upper` が **個々の新観測値** に対する区間\n",
    "- 信頼区間（confidence interval）と予測区間の違い：\n",
    "  - CI: 母平均の範囲 → 期待値の不確実性\n",
    "  - **PI: 次の1点が入る範囲** → 実際の価格変動を含む（より広い）\n",
    "- 分割: 直近252日をテストセット\n",
]))

cells.append(code([
    "TEST_SIZE = 252\n",
    "feat_train = feat.iloc[:-TEST_SIZE]\n",
    "feat_test  = feat.iloc[-TEST_SIZE:]\n",
    "\n",
    "y_train = feat_train['close_ret']\n",
    "y_test  = feat_test['close_ret']\n",
    "\n",
    "X_train = sm.add_constant(feat_train[FEATURE_COLS])\n",
    "X_test  = sm.add_constant(feat_test[FEATURE_COLS])\n",
    "\n",
    "ols = sm.OLS(y_train, X_train).fit()\n",
    "\n",
    "print(f'Train: {feat_train.index[0].date()} to {feat_train.index[-1].date()}  (n={len(feat_train)})')\n",
    "print(f'Test : {feat_test.index[0].date()}  to {feat_test.index[-1].date()}   (n={len(feat_test)})')\n",
    "print()\n",
    "print(f'In-sample  R²    : {ols.rsquared:.4f}')\n",
    "print(f'Adj. R²          : {ols.rsquared_adj:.4f}')\n",
    "\n",
    "# Out-of-sample R²\n",
    "y_pred_test = ols.predict(X_test)\n",
    "ss_res = ((y_test - y_pred_test) ** 2).sum()\n",
    "ss_tot = ((y_test - y_test.mean()) ** 2).sum()\n",
    "oos_r2 = 1 - ss_res / ss_tot\n",
    "print(f'Out-of-sample R² : {oos_r2:.4f}')\n",
    "\n",
    "dir_acc = (np.sign(y_pred_test) == np.sign(y_test)).mean()\n",
    "print(f'Directional acc. : {dir_acc:.3f}')\n",
]))

cells.append(code([
    "# Top coefficients by absolute value\n",
    "coef = pd.Series(ols.params[1:], index=FEATURE_COLS)  # skip const\n",
    "pval = pd.Series(ols.pvalues[1:], index=FEATURE_COLS)\n",
    "\n",
    "coef_df = pd.DataFrame({'Coef': coef, 'p-value': pval})\n",
    "coef_df['Sig'] = coef_df['p-value'].apply(\n",
    "    lambda p: '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else '.' if p < 0.10 else ''\n",
    ")\n",
    "coef_df = coef_df.reindex(coef.abs().sort_values(ascending=False).index)\n",
    "\n",
    "print('OLS Coefficients (sorted by |coef|):')\n",
    "display(\n",
    "    coef_df.style\n",
    "    .format({'Coef': '{:+.5f}', 'p-value': '{:.4f}'})\n",
    "    .background_gradient(subset=['Coef'], cmap='RdBu')\n",
    ")\n",
]))

# ---------- SECTION 5 -------------------------------------------------------
cells.append(md([
    "## 5. 予測区間のバックテスト / Prediction Interval Backtest\n",
    "\n",
    "正しく推定された90%予測区間なら、実績値がその区間に収まる確率が約90%のはずです。  \n",
    "これを **カバレッジ率（coverage rate）** と呼びます。カバレッジが90%を大幅に下回る場合、  \n",
    "モデルが不確実性を過小評価していることを示します。\n",
]))

cells.append(code([
    "# OLS prediction intervals on test set\n",
    "pred_result = ols.get_prediction(X_test)\n",
    "pred_frame  = pred_result.summary_frame(alpha=0.10)  # 90% prediction interval\n",
    "\n",
    "# Coverage rate: how often does actual fall inside the interval?\n",
    "within = (\n",
    "    (y_test.values >= pred_frame['obs_ci_lower'].values) &\n",
    "    (y_test.values <= pred_frame['obs_ci_upper'].values)\n",
    ").mean()\n",
    "\n",
    "print(f'=== Prediction Interval Backtest (Test period: {len(y_test)} days) ===')\n",
    "print(f'Theoretical coverage : 90.0%')\n",
    "print(f'Actual coverage      : {within:.1%}')\n",
    "print()\n",
    "\n",
    "# Also compute directional accuracy\n",
    "y_pred_mid = pred_frame['mean'].values\n",
    "dir_acc    = (np.sign(y_pred_mid) == np.sign(y_test.values)).mean()\n",
    "print(f'Dir. Accuracy        : {dir_acc:.3f}')\n",
    "print()\n",
    "print('Interval width stats:')\n",
    "interval_width = pred_frame['obs_ci_upper'] - pred_frame['obs_ci_lower']\n",
    "print(f'  Mean width: {interval_width.mean():.4f} ({interval_width.mean()*100:.2f}%)')\n",
    "print(f'  Max width : {interval_width.max():.4f} ({interval_width.max()*100:.2f}%)')\n",
]))

cells.append(code([
    "# Plot: predicted range vs actual (test period)\n",
    "prev_close_test = nk['Close'].reindex(feat_test.index).shift(1)\n",
    "\n",
    "pred_price_mid   = prev_close_test * (1 + pred_frame['mean'].values)\n",
    "pred_price_lower = prev_close_test * (1 + pred_frame['obs_ci_lower'].values)\n",
    "pred_price_upper = prev_close_test * (1 + pred_frame['obs_ci_upper'].values)\n",
    "actual_price     = nk['Close'].reindex(feat_test.index)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 5))\n",
    "ax.fill_between(\n",
    "    feat_test.index, pred_price_lower, pred_price_upper,\n",
    "    alpha=0.25, color='steelblue', label='90% Prediction Interval'\n",
    ")\n",
    "ax.plot(feat_test.index, pred_price_mid,\n",
    "        color='steelblue', lw=1.2, label='Predicted (Mid)')\n",
    "ax.plot(feat_test.index, actual_price.values,\n",
    "        color='black', lw=1.0, alpha=0.8, label='Actual Close')\n",
    "ax.set_ylabel('Nikkei 225 (JPY)')\n",
    "ax.set_title(f'Close Price Prediction & Prediction Interval (Test Period) | Coverage: {within:.1%}')\n",
    "ax.legend()\n",
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))\n",
    "ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:,.0f}'))\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/08_02_backtest_range.png', dpi=150)\n",
    "plt.show()\n",
]))

# ---------- SECTION 6 -------------------------------------------------------
cells.append(md([
    "## 6. 本日の終値予測 / Today's Close Price Prediction\n",
    "\n",
    "直近（最新）の特徴量を使って本日の終値予測とレンジを出力します。\n",
    "\n",
    "> **注意**: 本日の ADR・マクロデータが反映されるのは、  \n",
    "> 日本時間 8:00 AM（米国市場クローズ後）以降にノートブックを実行した場合です。  \n",
    "> それ以前の実行では前営業日のデータが使用されます。\n",
]))

cells.append(code([
    "# Use the last row of feat as 'today's' feature vector\n",
    "today_date = feat.index[-1]\n",
    "x_today    = feat.iloc[-1:][FEATURE_COLS]\n",
    "x_today_sm = sm.add_constant(x_today, has_constant='add')\n",
    "\n",
    "# OLS prediction + 90% prediction interval\n",
    "pred_today = ols.get_prediction(x_today_sm)\n",
    "pf = pred_today.summary_frame(alpha=0.10)\n",
    "\n",
    "pred_ret   = float(pf['mean'].iloc[0])\n",
    "lower_ret  = float(pf['obs_ci_lower'].iloc[0])\n",
    "upper_ret  = float(pf['obs_ci_upper'].iloc[0])\n",
    "\n",
    "# Convert return to price\n",
    "prev_close = float(nk['Close'].loc[:today_date].iloc[-2])  # yesterday's close\n",
    "pred_price = prev_close * (1 + pred_ret)\n",
    "lower_price= prev_close * (1 + lower_ret)\n",
    "upper_price= prev_close * (1 + upper_ret)\n",
    "\n",
    "# ================================================================\n",
    "print('=' * 50)\n",
    "print(f'  Nikkei 225 Close Prediction for {today_date.strftime(\"%Y-%m-%d\")}')\n",
    "print('=' * 50)\n",
    "print(f'  Prev Close  :  {prev_close:>10,.1f} JPY')\n",
    "print()\n",
    "print(f'  Pred Close  :  {pred_price:>10,.1f} JPY  ({pred_ret:+.2%})')\n",
    "print()\n",
    "print(f'  Prediction Range (90% Prediction Interval):')\n",
    "print(f'    Lower ( 5%) :  {lower_price:>10,.1f} JPY  ({lower_ret:+.2%})')\n",
    "print(f'    Mid   (50%) :  {pred_price:>10,.1f} JPY  ({pred_ret:+.2%})')\n",
    "print(f'    Upper (95%) :  {upper_price:>10,.1f} JPY  ({upper_ret:+.2%})')\n",
    "print('=' * 50)\n",
    "print()\n",
    "print(f'  Model Info:')\n",
    "print(f'    Training period : {feat_train.index[0].date()} to {feat_train.index[-1].date()}')\n",
    "print(f'    Features        : {len(FEATURE_COLS)} ({len(TECH_COLS)} technical + {len(valid_pairs)} ADR + {len(MACRO_COLS)} macro)')\n",
    "print(f'    OOS Dir. Acc.   : {dir_acc:.1%}')\n",
    "print(f'    Test coverage   : {within:.1%}  (theoretical 90.0%)')\n",
    "print('=' * 50)\n",
]))

cells.append(code([
    "# --- Gauge-style visualization of predicted range ---\n",
    "fig, ax = plt.subplots(figsize=(10, 3))\n",
    "\n",
    "# Horizontal bar showing range and prediction\n",
    "ax.barh(0, upper_price - lower_price, left=lower_price,\n",
    "        height=0.4, color='lightsteelblue', alpha=0.8, label='90% Prediction Interval')\n",
    "ax.barh(0, 0, left=lower_price, height=0.4, color='none',\n",
    "        edgecolor='steelblue', linewidth=2)\n",
    "\n",
    "# Prediction point\n",
    "ax.plot(pred_price, 0, 'D', markersize=12, color='steelblue',\n",
    "        zorder=5, label=f'Pred Close: {pred_price:,.0f} JPY')\n",
    "\n",
    "# Previous close\n",
    "ax.axvline(prev_close, color='grey', lw=1.5, ls='--',\n",
    "           label=f'Prev Close: {prev_close:,.0f} JPY')\n",
    "\n",
    "# Labels for bounds\n",
    "y_off = 0.28\n",
    "ax.text(lower_price, y_off, f'{lower_price:,.0f}\\n({lower_ret:+.2%})',\n",
    "        ha='center', va='bottom', fontsize=9, color='steelblue')\n",
    "ax.text(upper_price, y_off, f'{upper_price:,.0f}\\n({upper_ret:+.2%})',\n",
    "        ha='center', va='bottom', fontsize=9, color='steelblue')\n",
    "ax.text(pred_price, -y_off, f'{pred_price:,.0f} JPY\\n({pred_ret:+.2%})',\n",
    "        ha='center', va='top', fontsize=10, color='steelblue', fontweight='bold')\n",
    "\n",
    "ax.set_yticks([])\n",
    "ax.set_xlabel('Nikkei 225 Close Price (JPY)')\n",
    "ax.set_title(f'Nikkei 225 Close Prediction & 90% Prediction Range  |  {today_date.strftime(\"%Y-%m-%d\")}')\n",
    "ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:,.0f}'))\n",
    "ax.legend(loc='upper right')\n",
    "\n",
    "margin = (upper_price - lower_price) * 0.3\n",
    "ax.set_xlim(lower_price - margin, upper_price + margin)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{OUTPUT_FIGS}/08_03_prediction_gauge.png', dpi=150)\n",
    "plt.show()\n",
    "\n",
    "print('\\nDisclaimer: For educational purposes only. Do not use for actual investment decisions.')\n",
]))

# ---------- NOTEBOOK JSON ---------------------------------------------------
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
    },
    "cells": cells,
}

out_path = r'C:\Users\admin\Nikkei_Analysis\notebooks\08_close_prediction.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print('08_close_prediction.ipynb created')
